"""initial tables

Revision ID: 937cb6bd3ab4
Revises: 
Create Date: 2026-03-29 16:12:59.231605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '937cb6bd3ab4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_name', sa.String(length=50), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operator_name')
    )
    op.create_table('streets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teryt_sym_ul', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=250), nullable=False),
    sa.Column('street_type', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=50), server_default='Lublin', nullable=False),
    sa.Column('geojson', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teryt_sym_ul')
    )
    op.create_index('idx_streets_name', 'streets', ['name'], unique=False)
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('rodo_consent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('night_sms_consent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('unsubscribe_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unsubscribe_token')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), server_default='dispatcher', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=50), server_default='mpwik', nullable=False),
    sa.Column('street_id', sa.Integer(), nullable=True),
    sa.Column('street_name', sa.String(length=200), nullable=False),
    sa.Column('house_number_from', sa.String(length=10), nullable=True),
    sa.Column('house_number_to', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='zgloszona', nullable=False),
    sa.Column('estimated_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('geojson_segment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['street_id'], ['streets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_created', 'events', ['created_at'], unique=False)
    op.create_index('idx_events_source', 'events', ['source'], unique=False)
    op.create_index('idx_events_status', 'events', ['status'], unique=False)
    op.create_index('idx_events_street', 'events', ['street_id'], unique=False)
    op.create_table('subscriber_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('street_id', sa.Integer(), nullable=True),
    sa.Column('street_name', sa.String(length=200), nullable=False),
    sa.Column('house_number', sa.String(length=10), nullable=False),
    sa.Column('flat_number', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['street_id'], ['streets.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_subscriber_addresses_street', 'subscriber_addresses', ['street_id'], unique=False)
    op.create_table('event_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('subscriber_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('recipient', sa.String(length=100), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='sent', nullable=False),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_log')
    op.drop_table('event_history')
    op.drop_index('idx_subscriber_addresses_street', table_name='subscriber_addresses')
    op.drop_table('subscriber_addresses')
    op.drop_index('idx_events_street', table_name='events')
    op.drop_index('idx_events_status', table_name='events')
    op.drop_index('idx_events_source', table_name='events')
    op.drop_index('idx_events_created', table_name='events')
    op.drop_table('events')
    op.drop_table('users')
    op.drop_table('subscribers')
    op.drop_index('idx_streets_name', table_name='streets')
    op.drop_table('streets')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
